version: "3"

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    volumes:
      - ./scripts:/scripts
    command: /bin/bash -c "chmod +x /scripts/main.sh && /scripts/main.sh && while true; do sleep 1; done"